# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modelsim_10.5/win64
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.cache/wt} [current_project]
set_property parent.project_path {E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.0 [current_project]
set_property ip_repo_paths {
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/ip_repo/parallel_ntt_2.0}
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/ip_repo/parallel_ntt_2.0}
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/ip_repo/parallel_ntt_2.0}
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/ip_repo/parallel_ntt_1.0}
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/user_rtl}
  {e:/Dropbox/FHE/my project/Parallel NTT/hardware/ip_repo/parallel_ntt_1.0/src/mult_gen_64x32}
} [current_project]
set_property ip_output_repo {e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {{E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/user_rtl}} [current_fileset]
read_verilog -library xil_defaultlib {{E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/user_rtl/parallel_ntt_0_wrapper.v}}
read_ip -quiet {{E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/parallel_ntt_0.xci}}
set_property used_in_implementation false [get_files -all {{e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/user_constrain.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/user_rtl/usr_constrain.xdc}}
set_property used_in_implementation false [get_files {{E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/user_rtl/usr_constrain.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top parallel_ntt_0_wrapper -part xczu7ev-ffvc1156-2-e -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef parallel_ntt_0_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file parallel_ntt_0_wrapper_utilization_synth.rpt -pb parallel_ntt_0_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
