######################################################################
#
# File name : parallel_ntt_0_butterfly_tb_compile.do
# Created on: Thu Nov 18 17:27:20 +0800 2021
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/work
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim

D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../user_rtl" \
"parallel_ntt_0_butterfly_tb_time_impl.v" \
"../../../../../user_rtl/parallel_ntt_0_butterfly_tb.v" \


quit -force

