# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/parallel_ntt_0.xci
# IP: The module: 'parallel_ntt_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/mult_gen_32x32/mult_gen_32x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_32x32 || ORIG_REF_NAME==mult_gen_32x32} -quiet] -quiet

# IP: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/mult_gen_64x33/mult_gen_64x33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_64x33 || ORIG_REF_NAME==mult_gen_64x33} -quiet] -quiet

# XDC: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/user_constrain.xdc
# XDC: The top module name and the constraint reference have the same name: 'parallel_ntt_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/parallel_ntt_0.xci
# IP: The module: 'parallel_ntt_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/mult_gen_32x32/mult_gen_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_32x32 || ORIG_REF_NAME==mult_gen_32x32} -quiet] -quiet

# IP: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/mult_gen_64x33/mult_gen_64x33.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_64x33 || ORIG_REF_NAME==mult_gen_64x33} -quiet] -quiet

# XDC: e:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.srcs/sources_1/ip/parallel_ntt_0/src/user_constrain.xdc
# XDC: The top module name and the constraint reference have the same name: 'parallel_ntt_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
