######################################################################
#
# File name : parallel_ntt_0_butterfly_tb_simulate.do
# Created on: Fri Nov 19 15:38:47 +0800 2021
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.parallel_ntt_0_butterfly_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {parallel_ntt_0_butterfly_tb_wave.do}

view wave
view structure
view signals

do {parallel_ntt_0_butterfly_tb.udo}

run 1000ns
