######################################################################
#
# File name : parallel_ntt_0_butterfly_tb_wave.do
# Created on: Tue Nov 16 14:34:15 +0800 2021
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
