######################################################################
#
# File name : parallel_ntt_0_butterfly_tb.udo
# Created on: Tue Nov 16 14:34:15 +0800 2021
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
