######################################################################
#
# File name : parallel_ntt_0_butterfly_tb.udo
# Created on: Mon Dec 06 16:27:58 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}