######################################################################
#
# File name : parallel_ntt_0_butterfly_tb_wave.do
# Created on: Sun Dec 26 12:25:02 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
