######################################################################
#
# File name : parallel_ntt_0_butterfly_tb_compile.do
# Created on: Sun Feb 06 16:54:29 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/work
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim

D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/mult_gen_32x32/sim/mult_gen_32x32.vhd" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/mult_gen_64x33/sim/mult_gen_64x33.vhd" \

D:\\modelsim_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../user_rtl" "+incdir+../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/hdl/parallel_ntt_v2_0_S_AXIS.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/NTT_processor.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/mem_sp.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/Barret_reduce.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/parallel_NTT_top.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/src/mem_dp.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/hdl/parallel_ntt_v2_0_M_AXIS.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/hdl/parallel_ntt_v2_0.v" \
"../../../../parallel_NTT.ip_user_files/ip/parallel_ntt_0/sim/parallel_ntt_0.v" \
"../../../../user_rtl/parallel_ntt_0_wrapper.v" \
"../../../../user_rtl/parallel_ntt_0_butterfly_tb.v" \

# compile glbl module
D:\\modelsim_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

