webtalk_init -webtalk_dir E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.sim/sim_ntt/behav/xsim/xsim.dir/parallel_ntt_0_butterfly_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 22 12:31:27 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d08e20de-02b4-47f5-a160-d1fcfcbd79a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b5319ea4d1204568bed12873f350a247" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "29664_KB" -context "xsim\\usage"
webtalk_transmit -clientid 972914743 -regid "" -xml E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.sim/sim_ntt/behav/xsim/xsim.dir/parallel_ntt_0_butterfly_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.sim/sim_ntt/behav/xsim/xsim.dir/parallel_ntt_0_butterfly_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Dropbox/FHE/my project/Parallel NTT/hardware/parallel_NTT/parallel_NTT.sim/sim_ntt/behav/xsim/xsim.dir/parallel_ntt_0_butterfly_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
